# -*- coding: utf-8 -*-
"""Core Assignment: Python DA Assignment 1 – Data Analysis using NumPy and Pandas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVGI0sAvuqwaltDF4QNtnifJ0sV5IjhH

## Section 1: NumPy Array Operations
"""

import numpy as np

#  Create 1D NumPy array for Week 1
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

#  Inspection and properties
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Total Elements:", temperatures_w1.size)

#  Array Operations: Celsius to Fahrenheit
temperatures_fahrenheit = (temperatures_w1 * 9/5) + 32
print("Fahrenheit:", temperatures_fahrenheit)

print("Max Temperature:", np.max(temperatures_w1))
print("Min Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))

#  Slicing and Indexing
print("First 3 Days:", temperatures_w1[:3])
print("Weekend (last 2 days):", temperatures_w1[-2:])
print("Middle 3 Days:", temperatures_w1[2:5])

#  Create 2D Array (Week 1 + Week 2)
temperatures_w2 = np.array([19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1])
temperatures = np.array([temperatures_w1, temperatures_w2])

#  2D Array Inspection and Slicing
print("2D Shape:", temperatures.shape)
print("2D Data Type:", temperatures.dtype)
print("2D Total Elements:", temperatures.size)

print("Week 1 Temperatures:", temperatures[0])
print("Week 2 Temperatures:", temperatures[1])
print("Weekend Temps (Both Weeks):", temperatures[:, -2:])

"""## Section 2 – Pandas Series"""

import pandas as pd

marks = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

print("Marks series:")
print(marks)


#  Integer index position of 1st rank student (index 0)
print("\nMark of 1st rank (integer index):", marks[0])

#  loc accessor for top 3 ranks
print("\nTop 3 rank marks using loc:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# iloc accessor for 3rd rank
print("\nMark of 3rd rank using iloc:", marks.iloc[2])

#  Boolean mask: marks > 90
print("\nRanks with marks > 90:")
print(marks[marks > 90])

#Data manipulation
#  Update 1st rank to 100
marks['Rank1'] = 100
print("\nUpdated Mark for Rank1:", marks['Rank1'])

#  Remove last rank
marks.drop('Rank5', inplace=True)
print("\nAfter removing Rank5:\n", marks)

#  Calculate CGPA (mark / 10)
cgpa = marks / 10
print("\nCGPA (marks / 10):\n", cgpa)

import pandas as pd

# Creating Data frame

data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)
transactions.set_index('TransactionID', inplace=True)

print("Transactions DataFrame:\n", transactions)

#Data exploration

print("\nDataFrame Head:")
print(transactions.head())

print("\nDataFrame Tail:")
print(transactions.tail())

print("\nShape:", transactions.shape)
print("Columns:", transactions.columns.tolist())
print("Data Types:\n", transactions.dtypes)

import pandas as pd

# Creating Data frame
data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)
transactions.set_index('TransactionID', inplace=True)

#Column and row  filterig

# a) Only ProductCategory & Amount
print("\nSelected Columns:\n", transactions[['ProductCategory', 'Amount']])

# b) Last 3 columns using iloc
print("\nLast 3 Columns:\n", transactions.iloc[:, -3:])

# c) Filter Region is 'North' & Amount > 200
print("\nFilter: Region is North & Amount > 200\n",
      transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])

# d) ProductCategory counts
print("\nValue Counts for ProductCategory:\n", transactions['ProductCategory'].value_counts())

# e) Unique Regions
print("\nUnique Regions:", transactions['Region'].unique())

# f) Group by Region → Mean Amount
print("\nMean Amount by Region:\n", transactions.groupby('Region')['Amount'].mean())

import pandas as pd

# Creating Data frame
data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)
transactions.set_index('TransactionID', inplace=True)

#Manipulating data frame
# a) Modify Amount for TransactionID 102
transactions.loc[102, 'Amount'] = 165

# b) Add Discount column (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10

# c) Remove row with TransactionID 109
transactions.drop(109, inplace=True)

# d) Delete Discount column
transactions.drop('Discount', axis=1, inplace=True)

print("\nFinal DataFrame:\n", transactions)